---
abstract: 'Dancer plugin for Net::NodeTransformator'
author:
  - 'David Zurborg <zurborg@cpan.org>'
build_requires:
  Dancer::Test: '0'
  Env::Path: '0'
  Module::Signature: '0'
  Socket: '0'
  Test::More: '0'
  Test::Most: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.143240'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Plugin-Transformator
requires:
  Dancer: '0'
  Dancer::Plugin: '0'
  Net::NodeTransformator: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/zurborg/libdancer-plugin-transformator-perl/issues
  homepage: https://github.com/zurborg/libdancer-plugin-transformator-perl
  repository: https://github.com/zurborg/libdancer-plugin-transformator-perl.git
version: '0.001'
